### ISSUE TITLE
Incorrect `Ranges overlap` and `identical boundaries` error while parsing maven version range

### ISSUE THREAD

**Issue by keshav-space** [aboutcode-org/univers#142]
```python
>>> from univers.version_range import MavenVersionRange
>>> MavenVersionRange.from_native("[3.0.0,3.1.1),(,2.3.4)")
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "../univers/version_range.py", line 784, in from_native
    restrictions = maven.VersionRange(string).restrictions
  File "../univers/maven.py", line 226, in __init__
    raise VersionRangeParseError("Ranges overlap: %s" % spec)
univers.maven.VersionRangeParseError: Ranges overlap: [3.0.0,3.1.1),(,2.3.4)
```

```python
>>> from univers.version_range import MavenVersionRange
>>> MavenVersionRange.from_native("[5.0,5.0]")
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "../univers/version_range.py", line 784, in from_native
    restrictions = maven.VersionRange(string).restrictions
  File "../univers/maven.py", line 219, in __init__
    restriction = Restriction(_spec[0 : close + 1])
  File "../univers/maven.py", line 81, in __init__
    raise RestrictionParseError("Range cannot have identical boundaries: %s" % spec)
univers.maven.RestrictionParseError: Range cannot have identical boundaries: [5.0,5.0]
```

- Also see https://github.com/aboutcode-org/vulnerablecode/issues/1578

**Comment by PlayerIUnknown** [comment]
Hi, I am working on this issue and have solved the 'identical boundaries' bit. Just wanted to get some more information about what do you think is causing the 'range overlap' issue? I will add a PR once I fix both the mentioned errors.

**Comment by KunalG67** [comment]
I looked into the "Ranges overlap" case here ([3.0.0,3.1.1),(,2.3.4)) and compared it against Maven's actual reference implementation (org.apache.maven.artifact.versioning.VersionRange, checked across 2.2.1 through 4.0.0-rc-1).

Maven's parser does the exact same check univers does here:

java
if (upperBound != null) {
    if (restriction.getLowerBound() == null
            || restriction.getLowerBound().compareTo(upperBound) < 0) {
        throw new InvalidVersionSpecificationException("Ranges overlap: " + spec);
    }
}

This requires restrictions to be listed in strictly ascending order, each one's lower bound must be greater than or equal to the previous restriction's upper bound. (,2.3.4) appearing after [3.0.0,3.1.1) violates that ordering (it should come first: (,2.3.4),[3.0.0,3.1.1)), and real Maven throws the same Ranges overlap exception for this exact input, not just univers.

So I don't think this particular example is a bug, univers matches upstream Maven behavior here. It might be worth keeping the input as-is but improving the error message (something like "Restrictions must be in ascending order" instead of "Ranges overlap", since that's the actual problem), but the rejection itself looks correct.

This should unblock #201, @apoorva-01, since the identical-boundaries fix in that PR looks correct and independent of this ordering question.
